### ISSUE TITLE
Add ability to upload attachments to check requests, vendor receipts, and in-kind donations

### ISSUE THREAD

**Issue by GoogleCodeExporter** [babybunny/rebuildingtogethercaptain#172]
```
What steps will reproduce the problem?
currently, the attachments have to be sent through a separate e-mail as there 
is no function for adding attachments in ROOMS.

What is the expected output? What do you see instead?
it would be nice if attachment(s) could be provided with check requests, vendor 
receipts, and in-kind donations so those details are included in one place.


Please provide any additional information below.

```

Original issue reported on code.google.com by `c...@rebuildingtogetherpeninsula.org` on 3 Jun 2013 at 5:38

**Comment by babybunny** [comment]
We used to have some upload capability.  It was for item images.  

There are a few file upload libraries for Backbone

looks good
https://github.com/homeslicesolutions/backbone-model-file-upload

roll your own
https://estebanpastorino.com/2013/09/27/simple-file-uploads-with-backbone-dot-js/

obscure but may work
http://sroze.github.io/backbone-upload-manager/
