### ISSUE TITLE
remove the old "Site" object

### ISSUE THREAD

**Issue by GoogleCodeExporter** [babybunny/rebuildingtogethercaptain#191]
```
we use "NewSite" now


```

Original issue reported on code.google.com by `babybu...@gmail.com` on 20 Jul 2014 at 11:23

**Comment by babybunny** [comment]
I removed a bunch of old code and pushed to version issue191. 

It's hard to know if this will work in all cases. I'm a bit concerned about captains editing sites.

**Comment by babybunny** [comment]
removed unused reference
