### ISSUE TITLE
add mileage to stafftime input 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [babybunny/rebuildingtogethercaptain#211]
```
on this form
http://issue205.rebuildingtogethercaptain-hrd.appspot.com/room/stafftime/new/579
6197079973888/

add mileage (number) next to hours

add mileage rate in StaffPosition 

add mileage column in reporting summary staff time section
```

Original issue reported on code.google.com by `babybu...@gmail.com` on 24 Jul 2015 at 12:21

**Comment by babybunny** [comment]
[201508131617.pdf](https://github.com/babybunny/rebuildingtogethercaptain/files/29477/201508131617.pdf)

this mockup has a separate section for mileage.

**Comment by babybunny** [comment]
added mileage to datastore and forms.  it can now be input and has basic reporting.
