### ISSUE TITLE
enable billing

### ISSUE THREAD

**Issue by GoogleCodeExporter** [babybunny/rebuildingtogethercaptain#217]
```
https://console.developers.google.com/project/rebuildingtogethercaptain-hrd/sett
ings

shows ROOMS billing account is disabled. 


```

Original issue reported on code.google.com by `babybu...@gmail.com` on 10 Aug 2015 at 3:52

**Comment by babybunny** [comment]
Cari and I took care of this over the phone.  App has billing enabled and $5/day budget.
