### ISSUE TITLE
lines not wrapping on Reporting Summary

### ISSUE THREAD

**Issue by babybunny** [babybunny/rebuildingtogethercaptain#220]
Cari reported, causes problems especially when printing.

[201508131617.pdf](https://github.com/babybunny/rebuildingtogethercaptain/files/29467/201508131617.pdf)

**Comment by babybunny** [comment]
I don't see the problem.  looks like all info is present.

**Comment by babybunny** [comment]
I think it's fixed.   Looks OK now (different from earlier example) for the same site:
http://rebuildingtogethercaptain.appspot.com/room/site/summary/5796197079973888/

**Comment by caripang** [comment]
Looks like it's working!  Thanks so much, Luke!




Cari Pang Chen | Associate Director

Rebuilding Together Peninsula
841 Kaynyne Street | Redwood City | 94063
(W): 650.366.6597 x224 | (gVoice): 650.451-1787
www.RebuildingTogetherPeninsula.org
<http://www.rebuildingtogetherpeninsula.org/>

*A safe and healthy home for every person*

Note: When visiting our office, please note that we have a back parking lot
accessible via 852 Charter Street, between Bay & Spring.
