### ISSUE TITLE
Instructions to Captains

### ISSUE THREAD

**Issue by caripang** [babybunny/rebuildingtogethercaptain#225]

**Comment by caripang** [comment]
Orders need "Instructions to Captains" to be edited with Frank Hebscher replacing Adam Widmer as the contact.  It would be great if we had ability to edit this directly on our own.

**Comment by babybunny** [comment]
the "Instructions to Captains" are a field in the Order Sheet.  You can see all the Order Sheets here
http://rebuildingtogethercaptain.appspot.com/room/order_sheet/list

And each has an "edit sheet" link where you should be able to edit the Instructions.

**Comment by caripang** [comment]
Thanks!  Looks like it is ok with the Instructions - will have to see where
Adam's name had showed up earlier.  Glad we can edit and fix it!




Cari Pang Chen | Associate Director

Rebuilding Together Peninsula
841 Kaynyne Street | Redwood City | 94063
(W): 650.366.6597 x224 | (gVoice): 650.451-1787
www.RebuildingTogetherPeninsula.org
<http://www.rebuildingtogetherpeninsula.org/>

*A safe and healthy home for every person*

Note: When visiting our office, please note that we have a back parking lot
accessible via 852 Charter Street, between Bay & Spring.
