### ISSUE TITLE
Adding "Volunteer Sign-Up Page" link

### ISSUE THREAD

**Issue by caripang** [babybunny/rebuildingtogethercaptain#226]
Similar to how we have the "Site Photos" link set up, we would like to do one called "Volunteer Sign-Up Page" to link a Salesforce webpage that we create for sign-ups for each site.

**Comment by babybunny** [comment]
OK, it should be easy to add the link, but may be tricky to figure out how to refer to the ROOMS site in SalesForce.  What is the location of the Salesforce page (URL like http:// ... something)?

**Comment by caripang** [comment]
Yes - the URL is a really long Salesforce URL.  Here's an example:
http://rebuildingtogetherpeninsula.force.com/GW_Volunteers__VolunteersJobListingFS?&CampaignID=701U0000000rnvU

**Comment by babybunny** [comment]
Just add the link, text is "Volunteer signup"
value is a URL that Staff will enter. 

New field in the NewSite model.
Will come in from Staff data import.

**Comment by caripang** [comment]
Is it possible to add this to the "Edit Site info" page?  

We will not usually have the volunteer sign-up info ready for the staff data import.

**Comment by caripang** [comment]
@kate-mills , Just wondering when you'll be able to add this to the field list?  I am working on creating the links and want to make sure it's easy for the captains to know it's on ROOMS.

**Comment by kate-mills** [comment]
@caripang , I want to Confirm we are speaking about the same Form.  Are you referring to this form, 
http://rebuildingtogethercaptain.appspot.com/room/site/new
 Titled:  'Adding new Site' and  'Site Info'  for Site Captains.

Is this where I should add a new field labeled, "Volunteer signup"  and the value will be whatever the captain enters?

**Comment by caripang** [comment]
Thanks for checking, @kate-mills!  

Yes - that is exactly right.  From the "Edit Site Info" or "Adding New Site" page, there would be a new field labeled "Volunteer Signup Link" similar to "Photo link" and we'll update it with the link to the volunteer signup page.

**Comment by kate-mills** [comment]
@caripang , Excellent!!

**Comment by caripang** [comment]
@kate-mills, Thanks for adding the field.  I just tested it out on 17001DAL - the field is there, but nothing changes on the actual site page for them to see the link to the volunteer signup.  For the photo link, it says "Site Photos" if a link is there, so I think there must be a way for a "Volunteer Signup Page" link to show up on the site page when a link is put into the "Volunteer Signup Link" field is filled?

**Comment by kate-mills** [comment]
@caripang,
I see what you are saying!
I see what you entered in the form here:
http://rebuildingtogethercaptain.appspot.com/room/site/edit/5255931013103616/
But it is *not* showing up here:
http://rebuildingtogethercaptain.appspot.com/room/site/list/5255931013103616/


GOT IT!!  I'm on it right now!!
Katie

**Comment by caripang** [comment]
thank you!

Cari Pang Chen | Associate Director



Rebuilding Together Peninsula
841 Kaynyne Street | Redwood City | 94063
(W): 650.366.6597 x224 | (C): 650.451-1787
www.RTPeninsula.org <http://www.rebuildingtogetherpeninsula.org/>

*A safe and healthy home for every person*

Note: When visiting our office, please note that we have a back parking lot
accessible via 852 Charter Street, between Bay & Spring.

**Comment by kate-mills** [comment]
@caripang ,
I added the "Volunteer Signup Page" link to show up on the site page.
I also changed "Volunteer Signup" to "Volunteer Signup Link".
So, you will have to enter the link info again.  Hope that's not too much trouble.

**Comment by caripang** [comment]
Thanks!  I entered the link info again but unfortunately I still don't see it show up on the site page after it's been entered.

**Comment by kate-mills** [comment]
I'll check it out.  I't worked before I changed the names.  Sorry.

**Comment by kate-mills** [comment]
Cari!!

I see it here:
https://issue226-dot-rebuildingtogethercaptain-hrd.appspot.com/room/site/list/5255931013103616/

Finally!!📣

**Comment by caripang** [comment]
hurrah!  all set - thanks so much katie!

**Comment by andy-d** [comment]
fixed by f968418
