### ISSUE TITLE
Captain Login

### ISSUE THREAD

**Issue by caripang** [babybunny/rebuildingtogethercaptain#228]
It seems the captains are being directed to last year's sites rather than this year's sites, so I have to send them the direct site link to access this year's site.

Is it possible to have them go directly to their captain profile to edit any of their personal info and link to the appropriate site that they want to see?  Or default to the largest site # that they are linked to?  (the site #s should increase each year).

**Comment by caripang** [comment]
For Example: 
If bill tarangioli logs in, I'd like for  him to go to his captain home page:
http://rebuildingtogethercaptain.appspot.com/room/captain/edit/1687272/

ideally, the page would show projects listed from newest to oldest

Then he can click on the project he wants to view from there and bookmark it if he wants to.

**Comment by caripang** [comment]
this will be more urgent in the spring when we have all our NRD captains needing to access ROOMS in full force, but is still relevant to issue #341 that is flagged as a bug since we currently also cannot add captains to sites.

**Comment by caripang** [comment]
Thanks for working on this!  I logged in to see what this would look like and tried to create the attached example of what I hope this can look like:

- Header at top would have slightly revised wording (see the additional text in red)
- Possibly center the list of sites as well as part of the header, with a line break between each site to make it more obvious
- Possibly put some sort of outline or highlight the text in the header, including list of sites to draw their attention to what they're looking at (since they're used to logging in and only seeing one site at a time]

[ROOMS_Captain_revised_page.pdf](https://github.com/babybunny/rebuildingtogethercaptain/files/1352784/ROOMS_Captain_revised_page.pdf)

**Comment by caripang** [comment]
Hi Cari, Luke, and Andy,

This is urgent because we have captains trying to put Orders on ROOMs and they are having this difficulty. See what a captain just sent regarding seeing multiple (past NRD sites) and the confusion when making orders. I just spoke on the phone with this specific captain and he was trying to order a dumpster but it was going to a past NRD site and not this year's. I know there was discussion about having captains having access to see their past project sites, but it sounds like it is causing problems. 

Luke and Andy-Is there a way for you to still allow them to see past sites, but only adjust/ make orders for this current year? Or anything to make it less confusing for them? 

THANK YOU!

Talk soon,

Jo



On Wed, Feb 28, 2018 at 8:32 PM, Thompson Sako <tsako@pacbell.net> wrote:
Got in.
But the rooms has 9 jobs in it.
Anyway to delete the used ones?
Tom

**Comment by babybunny** [comment]
So just 2018 NRD sites for now?

**Comment by babybunny** [comment]
We do have a list of "active" programs.   I can restrict the sites on the captain page to the "active" ones.

**Comment by babybunny** [comment]
OK, just NRD 2018 for now, and will get the "active" thing in place once we have the program_key populated on all sites and a way to change a program's active / inactive status.
