### ISSUE TITLE
Formatting Requests for Reporting Summary and Staff Time Expenses

### ISSUE THREAD

**Issue by caripang** [babybunny/rebuildingtogethercaptain#231]
1) It would be very helpful if we could have some control page breaks so that they don't break between cells or overrun margins that make it difficult for printing.  A good example is 15596BEL because it is monstrous in terms of number of receipts and staff time.

2) It would be helpful if "Staff time" could consistently sorted on the reporting summary, just the way it's possible with orders and vendor expenses. For instance, 15615SAB allows them to sort as needed, but not 15596BEL.  It's unclear why it works on some report summaries and not others.  

3) Adjusting hourly and mileage rates based on activity date.   Instead of having tons of different staff positions to pick from with different rates, it would be great if we could just put in hourly and mileage rates on the back end for the staff positions that adjust based on activity date.  For instance, each position might need an adjustment every time the hourly rate changes (based on a raise or changes in workers comp rates) or the IRS mileage reimbursement rates change (typically every calendar year). 

Separate from the reporting summaries is an issue with deleting orders.  For some reason, I am able to do this but no other staff.  I thought my privileges were the same as theirs, but when they pull up a list of orders they don't have the option to delete any of them.  Is there a reason for this?

**Comment by babybunny** [comment]
moving #3 to different issue ...

**Comment by caripang** [comment]
15596BEL is in 2016SAH:
http://rebuildingtogethercaptain.appspot.com/room/site/list/6114737054023680/

**Comment by caripang** [comment]
closing this issue since all of these varied issues (sorry I put them all on one, Luke!) appear to have been resolved as of 9/25/2017.
