### ISSUE TITLE
Update Programs for 2017

### ISSUE THREAD

**Issue by kate-mills** [babybunny/rebuildingtogethercaptain#233]
'2017 NRD'
'2017 Safe'
'2017 Teambuild'

**Comment by caripang** [comment]
Awesome!!!  Thanks, Katie!  Hope you all have a great weekend!

Cari Pang Chen | Associate Director



Rebuilding Together Peninsula
841 Kaynyne Street | Redwood City | 94063
(W): 650.366.6597 x224 | (gVoice): 650.451-1787
www.RTPeninsula.org <http://www.rebuildingtogetherpeninsula.org/>

*A safe and healthy home for every person*

Note: When visiting our office, please note that we have a back parking lot
accessible via 852 Charter Street, between Bay & Spring.
