### ISSUE TITLE
2017 data import

### ISSUE THREAD

**Issue by babybunny** [babybunny/rebuildingtogethercaptain#237]
See this file for the list of fields I'm looking for.  also issue # 227.
https://github.com/babybunny/rebuildingtogethercaptain/blob/master/import_csv.py

Also there's a default announcement message that you can set.

**Comment by babybunny** [comment]
Cari, please dump the report of sites and captains as a sample of the format, I'll let you know if anything needs to change.

**Comment by babybunny** [comment]
Put it in a Google Sheet, share with babybunny@gmail.com.

**Comment by caripang** [comment]
We have a Salesforce Report called ROOMS Site Info, which I can export as an excel doc and import into Googledocs.

Here's the link to the google sheet I created: https://docs.google.com/a/rebuildingtogetherpeninsula.org/spreadsheets/d/1TdLchjV8R3W854PaMzZxUCg8e1nFWbOeNwLeHV27MEE/edit?usp=sharing

**Comment by caripang** [comment]
Captains info should also be sent as a separate sheet.

First, from staff page, "View a list of all Captains." 
Review list as a spreadsheet, adding any new captains and making sure the basic field info below is included:

"Site ID", OK
"First Name", OK
"Last Name", OK
"Name (note I used a formula,
and then copied and pasted in just the values)", ignore
"Project Role", OK
"Preferred Phone", Phone
"Email", OK
"New?" ignore

**Comment by babybunny** [comment]
Captains need a unique id that spans salesforce and ROOMS

**Comment by babybunny** [comment]
Took a look at the data in the spreadsheet.   What should we do with these fields:

1) Campaign Description	
This appears to be the stuff that was in the "Sponsor" field in the past.  Now it's got a bunch of CDBG stuff and a prefix "Sponsor:" on many entries.  


2) Repair Application: Name of Organization	
This used to be the recipient name, now it's mostly empty.  I can just use it, no problem, but it might be easier to fix up the data before import.


3) there are now four roof fields.  used to be just a single true/false "Roof?" field. 
Repair Application: Does your roof need repair?	
Repair Application: Are there active leaks in the roof?	
Repair Application: Roof Evaluation Required
Repair Application: Roof Issues

4) the announcement subject and announcement body are missing.  we can add them later.

**Comment by babybunny** [comment]
OK I'll tackle the import.

**Comment by caripang** [comment]
Captain's data added to "2017 captain data" tab of the googledoc that was shared earlier - "NRD 2017 upload ROOMS site info from Salesforce"  

Please let me know if you need more info for the captain portion of the upload.  

Billy is working on the larger master list for all the captains already in ROOMS.

**Comment by caripang** [comment]
Just confirming that I also added any new captains on the list for this year to ROOMS, so they just need to be linked to their site/type of captain for this year.

**Comment by babybunny** [comment]
download from google sheet 
https://docs.google.com/spreadsheets/d/1TdLchjV8R3W854PaMzZxUCg8e1nFWbOeNwLeHV27MEE/edit#gid=1835187538
as CSV.

ran into some technical problems - see issue #244.

ok, now site data is in.  Please take a quick look.

**Comment by caripang** [comment]
everything looks like it uploaded in the right places - thank you so much, Luke!

**Comment by caripang** [comment]
Quick question - what will be the best way to create a new captain now that we have the "ROOMS Captain ID" in the background?  

Billy is still planning to prepare a "master list" of "ROOMS captain IDs" from Salesforce for all the rest of the captains already in ROOMS.

aloha,
cari

**Comment by caripang** [comment]
oops!  never mind - saw the ROOMS Captain ID on the new captain field list.

Will send you the master list from Billy ASAP.

**Comment by babybunny** [comment]
Loaded captains.

Here are the errors, perhaps they can be fixed up manually through ROOMS.

ERROR:root:site 17015SAM does not exist, skipping
ERROR:root:site 17017RWC does not exist, skipping
ERROR:root:site 17024MEN does not exist, skipping
ERROR:root:site 17024MEN does not exist, skipping
ERROR:root:site 17028EPA does not exist, skipping
ERROR:root:site 17038MVW 17039MVW does not exist, skipping
ERROR:root:site 17038MVW 17039MVW does not exist, skipping
ERROR:root:site 17056EPA does not exist, skipping
