### ISSUE TITLE
Adjusting hourly and mileage rates

### ISSUE THREAD

**Issue by babybunny** [babybunny/rebuildingtogethercaptain#238]
Adjusting hourly and mileage rates based on activity date. Instead of having tons of different staff positions to pick from with different rates, it would be great if we could just put in hourly and mileage rates on the back end for the staff positions that adjust based on activity rate. For instance, each position might need an adjustment every time the hourly rate changes (based on a raise or changes in workers comp rates) or the IRS mileage reimbursement rates change (typically every calendar year).

**Comment by babybunny** [comment]
Add time ranges to properties of StaffPosition. 

Have the position name that the user sees be just the name, and choose the correct StaffPosition entity based on the date of the activity.

**Comment by babybunny** [comment]
Added a mechanism for this, but it depends (again) on adding the data in the backend and this time it's a little uglier.  Let's see if we can make it work in the short term. 

Instructions for adding the data:
https://github.com/babybunny/rebuildingtogethercaptain/wiki

**Comment by caripang** [comment]
Thanks for figuring this out.  It is complicated, but I'll work with David and Chris to update all of this info.
