### ISSUE TITLE
Captain list on ROOMS Site Page

### ISSUE THREAD

**Issue by caripang** [babybunny/rebuildingtogethercaptain#245]
Is it possible to have the Captains on a site page appear first by type (in alpha order - Construction then Volunteer) and then by name (in alpha order)?  This would be helpful for sites with lots of captains.

Site 17052MEN is a good example:
http://rebuildingtogethercaptain.appspot.com/room/site/list/6468747367809024/

**Comment by babybunny** [comment]
got it.
