### ISSUE TITLE
Bug when trying to submit orders 

### ISSUE THREAD

**Issue by caripang** [babybunny/rebuildingtogethercaptain#248]
This appears to be a problem for any order.  A coworker was trying to do this for site 17575SSF.

__________________________

AttributeError at /room/order/edit/5318590425202688/
'module' object has no attribute 'START_NEW_ORDER_SUBMIT'
Request Method:	POST
Request URL:	http://rebuildingtogethercaptain.appspot.com/room/order/edit/5318590425202688/
Exception Type:	AttributeError
Exception Value:	
'module' object has no attribute 'START_NEW_ORDER_SUBMIT'
Exception Location:	/base/data/home/apps/s~rebuildingtogethercaptain-hrd/issue191.399234398659958119/room/order.py in _OrderPut, line 394
Python Executable:	/base/
Python Version:	2.5.2
Python Path:	['/base/data/home/apps/s~rebuildingtogethercaptain-hrd/issue191.399234398659958119', '/base/data/home/runtimes/python/python_dist/lib/python25.zip', '/base/data/home/runtimes/python/python_lib/versions/third_party/django-1.0', '/base/data/home/runtimes/python/python_dist/lib/python2.5/', '/base/data/home/runtimes/python/python_dist/lib/python2.5/plat-linux3', '/base/data/home/runtimes/python/python_dist/lib/python2.5/lib-tk', '/base/data/home/runtimes/python/python_dist/lib/python2.5/lib-dynload', '/base/data/home/runtimes/python/python_lib/versions/1', '/base/data/home/apps/s~rebuildingtogethercaptain-hrd/issue191.399234398659958119/']
Server time:	Fri, 17 Feb 2017 15:30:38 +0000
Traceback Switch to copy-and-paste view

/base/data/home/runtimes/python/python_lib/versions/third_party/django-1.0/django/core/handlers/base.py in get_response
                response = callback(request, *callback_args, **callback_kwargs) ...
▶ Local vars
/base/data/home/apps/s~rebuildingtogethercaptain-hrd/issue191.399234398659958119/room/order.py in OrderEdit
  redirect, template_dict = _OrderEditInternal(request, user, order_id) ...
▶ Local vars
/base/data/home/apps/s~rebuildingtogethercaptain-hrd/issue191.399234398659958119/room/order.py in _OrderEditInternal
  return _OrderPut(request, user, order) ...
▶ Local vars
/base/data/home/apps/s~rebuildingtogethercaptain-hrd/issue191.399234398659958119/room/order.py in _OrderPut
  if not request.POST or request.POST['submit'] == views.START_NEW_ORDER_SUBMIT: ...
▶ Local vars
Request information

GET
No GET data
POST
Variable	Value
item_ah9zfnJlYnVpbGRpbmd0b2dldGhlcmNhcHRhaW4taHJkchYLEglPcmRlckl0ZW0YgICA6Nrn-QgM	
u''
item_ah9zfnJlYnVpbGRpbmd0b2dldGhlcmNhcHRhaW4taHJkchYLEglPcmRlckl0ZW0YgICA6K2ApAkM	
u''
item_ah9zfnJlYnVpbGRpbmd0b2dldGhlcmNhcHRhaW4taHJkchYLEglPcmRlckl0ZW0YgICA6KCd4ggM	
u''
notes	
u''
item_ah9zfnJlYnVpbGRpbmd0b2dldGhlcmNhcHRhaW4taHJkchYLEglPcmRlckl0ZW0YgICAqK2S_goM	
u'5'
item_ah9zfnJlYnVpbGRpbmd0b2dldGhlcmNhcHRhaW4taHJkchYLEglPcmRlckl0ZW0YgICA6J7b9QgM	
u''
submit	
u'Submit this order and proceed to delivery options'
site	
u'ah9zfnJlYnVpbGRpbmd0b2dldGhlcmNhcHRhaW4taHJkchQLEgdOZXdTaXRlGICAgKif7r4KDA'
item_ah9zfnJlYnVpbGRpbmd0b2dldGhlcmNhcHRhaW4taHJkchYLEglPcmRlckl0ZW0YgICA6OC0uwsM	
u''
item_ah9zfnJlYnVpbGRpbmd0b2dldGhlcmNhcHRhaW4taHJkchYLEglPcmRlckl0ZW0YgICAqK2nuQsM	
u''
item_ah9zfnJlYnVpbGRpbmd0b2dldGhlcmNhcHRhaW4taHJkchYLEglPcmRlckl0ZW0YgICA6NTq6AkM	
u''
item_ah9zfnJlYnVpbGRpbmd0b2dldGhlcmNhcHRhaW4taHJkchYLEglPcmRlckl0ZW0YgICA6LrwpAkM	
u''
item_ah9zfnJlYnVpbGRpbmd0b2dldGhlcmNhcHRhaW4taHJkchYLEglPcmRlckl0ZW0YgICA6NTq6AoM	
u''
item_ah9zfnJlYnVpbGRpbmd0b2dldGhlcmNhcHRhaW4taHJkchYLEglPcmRlckl0ZW0YgICA6LzPsQkM	
u''
item_ah9zfnJlYnVpbGRpbmd0b2dldGhlcmNhcHRhaW4taHJkchYLEglPcmRlckl0ZW0YgICA6KCJvQsM	
u''
COOKIES
Variable	Value
__utmz	
'79689751.1461295397.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none)'
__utmt	
'1'
ACSID	
'~AJKiYcHBxnkqdlCgM2-j6thB-RAuGVTtOCNbUKcbDPWqlkpylmEKxeB5PP6NlGqdtWZkqxbG_N02xUcDJ49gOvkt-bj_-Axlys8be4mqTUPOPIkYdsY_wtAOKsahzhM_ZUhEvWVpLOxs-wVu38dC3Y0Ei9EPMwQoNm-WaXH2vLYUGChcJaul9ye8CY7LeZW1Q509-qwHlnkY5hhVbX4stxVik6zTR0raE3d21Vt3xZMoyzd_huEmLDedUua_Pspa21N3tC0h0E7lxQkCuCCwDcZewj0XGPVXKR9yKVpWYMs_HdBzC0ltckzPWpih-FUNGqUiIkQOuZWvwn0W5byxHMyTiSZD6q16SS5roxPCZyreoIMXaO8SvCI'
__utma	
'79689751.38131064.1461295397.1487296876.1487345404.556'
__utmb	
'79689751.5.10.1487345404'
__utmc	
'79689751'
META
Variable	Value
APPENGINE_RUNTIME	
'python'
APPLICATION_ID	
's~rebuildingtogethercaptain-hrd'
AUTH_DOMAIN	
'gmail.com'
CONTENT_LENGTH	
'1140'
CONTENT_TYPE	
'application/x-www-form-urlencoded'
CURRENT_MODULE_ID	
'default'
CURRENT_VERSION_ID	
'issue191.399234398659958119'
DATACENTER	
'us2'
DEFAULT_VERSION_HOSTNAME	
'rebuildingtogethercaptain-hrd.appspot.com'
HTTPS	
'off'
HTTP_ACCEPT	
'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8'
HTTP_ACCEPT_LANGUAGE	
'en-US,en;q=0.8'
HTTP_CACHE_CONTROL	
'max-age=0'
HTTP_CONTENT_LENGTH	
'1140'
HTTP_CONTENT_TYPE	
'application/x-www-form-urlencoded'
HTTP_COOKIE	
'ACSID=~AJKiYcHBxnkqdlCgM2-j6thB-RAuGVTtOCNbUKcbDPWqlkpylmEKxeB5PP6NlGqdtWZkqxbG_N02xUcDJ49gOvkt-bj_-Axlys8be4mqTUPOPIkYdsY_wtAOKsahzhM_ZUhEvWVpLOxs-wVu38dC3Y0Ei9EPMwQoNm-WaXH2vLYUGChcJaul9ye8CY7LeZW1Q509-qwHlnkY5hhVbX4stxVik6zTR0raE3d21Vt3xZMoyzd_huEmLDedUua_Pspa21N3tC0h0E7lxQkCuCCwDcZewj0XGPVXKR9yKVpWYMs_HdBzC0ltckzPWpih-FUNGqUiIkQOuZWvwn0W5byxHMyTiSZD6q16SS5roxPCZyreoIMXaO8SvCI; __utmt=1; __utma=79689751.38131064.1461295397.1487296876.1487345404.556; __utmb=79689751.5.10.1487345404; __utmc=79689751; __utmz=79689751.1461295397.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none)'
HTTP_HOST	
'rebuildingtogethercaptain.appspot.com'
HTTP_ORIGIN	
'http://rebuildingtogethercaptain.appspot.com'
HTTP_REFERER	
'http://rebuildingtogethercaptain.appspot.com/room/order/new/5905966394507264/SAF/'
HTTP_UPGRADE_INSECURE_REQUESTS	
'1'
HTTP_USER_AGENT	
'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36'
HTTP_X_APPENGINE_CITY	
'redwood city'
HTTP_X_APPENGINE_CITYLATLONG	
'37.485215,-122.236355'
HTTP_X_APPENGINE_COUNTRY	
'US'
HTTP_X_APPENGINE_REGION	
'ca'
HTTP_X_CLOUD_TRACE_CONTEXT	
'5f9c8ce7c5f8a59ce903b7a56864da20/652942686324003954'
INSTANCE_ID	
'00c61b117c6f372f945635db8bdb96ffd45e5f95bf288ce73ac926fa290ef838fdb3fd554673824e'
PATH_INFO	
u'/room/order/edit/5318590425202688/'
PATH_TRANSLATED	
'/base/data/home/apps/s~rebuildingtogethercaptain-hrd/issue191.399234398659958119/main.py'
QUERY_STRING	
''
REMOTE_ADDR	
'76.14.79.217'
REQUEST_ID_HASH	
'D8E1E1C5'
REQUEST_LOG_ID	
'58a7171d00ff0a76a1d8e1e1c50001737e72656275696c64696e67746f6765746865726361707461696e2d68726400016973737565313931000100'
REQUEST_METHOD	
'POST'
SCRIPT_NAME	
u''
SERVER_NAME	
'rebuildingtogethercaptain.appspot.com'
SERVER_PORT	
'80'
SERVER_PROTOCOL	
'HTTP/1.1'
SERVER_SOFTWARE	
'Google App Engine/1.9.48'
TZ	
'UTC'
USER	
'apphosting'
USER_EMAIL	
'cari@rebuildingtogetherpeninsula.org'
USER_ID	
'100635658095976636722'
USER_IS_ADMIN	
'1'
USER_NICKNAME	
'cari'
USER_ORGANIZATION	
'rebuildingtogetherpeninsula.org'
wsgi.errors	
<cStringIO.StringO object at 0xd08ed906ac031068>
wsgi.input	
<cStringIO.StringI object at 0xd08ed906ad4ff4d8>
wsgi.multiprocess	
False
wsgi.multithread	
False
wsgi.run_once	
True
wsgi.url_scheme	
'http'
wsgi.version	
(1, 0)
Settings
Using settings module settings
Setting	Value
ABSOLUTE_URL_OVERRIDES	
{}
ADMINS	
(('Luke Stone', 'babybunny@gmail.com'),)
ADMIN_FOR	
()
ADMIN_MEDIA_PREFIX	
'/media/'
ALLOWED_INCLUDE_ROOTS	
()
APPEND_SLASH	
True
AUTHENTICATION_BACKENDS	
('django.contrib.auth.backends.ModelBackend',)
BANNED_IPS	
()
CACHE_BACKEND	
'locmem://'
CACHE_MIDDLEWARE_KEY_PREFIX	
''
CACHE_MIDDLEWARE_SECONDS	
600
COMMENTS_ALLOW_PROFANITIES	
False
COMMENTS_BANNED_USERS_GROUP	
None
COMMENTS_FIRST_FEW	
0
COMMENTS_MODERATORS_GROUP	
None
COMMENTS_SKETCHY_USERS_GROUP	
None
DATABASE_ENGINE	
'appengine'
DATABASE_HOST	
''
DATABASE_NAME	
''
DATABASE_OPTIONS	
{}
DATABASE_PASSWORD	
'********************'
DATABASE_PORT	
''
DATABASE_USER	
''
DATETIME_FORMAT	
'N j, Y, P'
DATE_FORMAT	
'N j, Y'
DEBUG	
True
DEBUG_PROPAGATE_EXCEPTIONS	
False
DEFAULT_CHARSET	
'utf-8'
DEFAULT_CONTENT_TYPE	
'text/html'
DEFAULT_FILE_STORAGE	
'django.core.files.storage.FileSystemStorage'
DEFAULT_FROM_EMAIL	
'webmaster@localhost'
DEFAULT_INDEX_TABLESPACE	
''
DEFAULT_TABLESPACE	
''
DISALLOWED_USER_AGENTS	
()
EMAIL_HOST	
''
EMAIL_HOST_PASSWORD	
'********************'
EMAIL_HOST_USER	
''
EMAIL_PORT	
25
EMAIL_SUBJECT_PREFIX	
'[Django] '
EMAIL_USE_TLS	
False
FILE_CHARSET	
'utf-8'
FILE_UPLOAD_HANDLERS	
('django.core.files.uploadhandler.MemoryFileUploadHandler', 'django.core.files.uploadhandler.TemporaryFileUploadHandler')
FILE_UPLOAD_MAX_MEMORY_SIZE	
2621440
FILE_UPLOAD_PERMISSIONS	
None
FILE_UPLOAD_TEMP_DIR	
None
FIXTURE_DIRS	
()
FORCE_SCRIPT_NAME	
None
IGNORABLE_404_ENDS	
('mail.pl', 'mailform.pl', 'mail.cgi', 'mailform.cgi', 'favicon.ico', '.php')
IGNORABLE_404_STARTS	
('/cgi-bin/', '/_vti_bin', '/_vti_inf')
INSTALLED_APPS	
('appengine_django', 'gaeunit', 'django.contrib.humanize')
INTERNAL_IPS	
()
JING_PATH	
'/usr/bin/jing'
LANGUAGES	
(('ar', 'Arabic'), ('bn', 'Bengali'), ('bg', 'Bulgarian'), ('ca', 'Catalan'), ('cs', 'Czech'), ('cy', 'Welsh'), ('da', 'Danish'), ('de', 'German'), ('el', 'Greek'), ('en', 'English'), ('es', 'Spanish'), ('et', 'Estonian'), ('es-ar', 'Argentinean Spanish'), ('eu', 'Basque'), ('fa', 'Persian'), ('fi', 'Finnish'), ('fr', 'French'), ('ga', 'Irish'), ('gl', 'Galician'), ('hu', 'Hungarian'), ('he', 'Hebrew'), ('hi', 'Hindi'), ('hr', 'Croatian'), ('is', 'Icelandic'), ('it', 'Italian'), ('ja', 'Japanese'), ('ka', 'Georgian'), ('ko', 'Korean'), ('km', 'Khmer'), ('kn', 'Kannada'), ('lv', 'Latvian'), ('lt', 'Lithuanian'), ('mk', 'Macedonian'), ('nl', 'Dutch'), ('no', 'Norwegian'), ('pl', 'Polish'), ('pt', 'Portuguese'), ('pt-br', 'Brazilian Portuguese'), ('ro', 'Romanian'), ('ru', 'Russian'), ('sk', 'Slovak'), ('sl', 'Slovenian'), ('sr', 'Serbian'), ('sv', 'Swedish'), ('ta', 'Tamil'), ('te', 'Telugu'), ('th', 'Thai'), ('tr', 'Turkish'), ('uk', 'Ukrainian'), ('zh-cn', 'Simplified Chinese'), ('zh-tw', 'Traditional Chinese'))
LANGUAGES_BIDI	
('he', 'ar', 'fa')
LANGUAGE_CODE	
'en-us'
LANGUAGE_COOKIE_NAME	
'django_language'
LOCALE_PATHS	
()
LOGIN_REDIRECT_URL	
'/accounts/profile/'
LOGIN_URL	
'/accounts/login/'
LOGOUT_URL	
'/accounts/logout/'
MANAGERS	
(('Luke Stone', 'babybunny@gmail.com'),)
MEDIA_ROOT	
''
MEDIA_URL	
''
MIDDLEWARE_CLASSES	
('django.middleware.common.CommonMiddleware',)
MONTH_DAY_FORMAT	
'F j'
PASSWORD_RESET_TIMEOUT_DAYS	
'********************'
PREPEND_WWW	
False
PROFANITIES_LIST	
'********************'
ROOT_PATH	
'/base/data/home/apps/s~rebuildingtogethercaptain-hrd/issue191.399234398659958119'
ROOT_URLCONF	
'urls'
SECRET_KEY	
'********************'
SEND_BROKEN_LINK_EMAILS	
False
SERIALIZATION_MODULES	
{'xml': 'appengine_django.serializer.xml'}
SERVER_EMAIL	
'root@localhost'
SESSION_COOKIE_AGE	
1209600
SESSION_COOKIE_DOMAIN	
None
SESSION_COOKIE_NAME	
'sessionid'
SESSION_COOKIE_PATH	
'/'
SESSION_COOKIE_SECURE	
False
SESSION_ENGINE	
'django.contrib.sessions.backends.db'
SESSION_EXPIRE_AT_BROWSER_CLOSE	
False
SESSION_FILE_PATH	
None
SESSION_SAVE_EVERY_REQUEST	
False
SETTINGS_MODULE	
'settings'
SITE_ID	
1
TEMPLATE_CONTEXT_PROCESSORS	
('django.core.context_processors.debug', 'django.core.context_processors.i18n')
TEMPLATE_DEBUG	
True
TEMPLATE_DIRS	
('/base/data/home/apps/s~rebuildingtogethercaptain-hrd/issue191.399234398659958119/templates', '/base/data/home/apps/s~rebuildingtogethercaptain-hrd/issue191.399234398659958119/room/templates', '/base/data/home/apps/s~rebuildingtogethercaptain-hrd/issue191.399234398659958119/staff/templates')
TEMPLATE_LOADERS	
('django.template.loaders.filesystem.load_template_source', 'django.template.loaders.app_directories.load_template_source')
TEMPLATE_STRING_IF_INVALID	
''
TEST_DATABASE_CHARSET	
None
TEST_DATABASE_COLLATION	
None
TEST_DATABASE_NAME	
None
TEST_RUNNER	
'django.test.simple.run_tests'
TIME_FORMAT	
'P'
TIME_ZONE	
'UTC'
TRANSACTIONS_MANAGED	
False
URL_VALIDATOR_USER_AGENT	
'Django/1.0.2 final (http://www.djangoproject.com)'
USE_ETAGS	
False
USE_I18N	
True
YEAR_MONTH_FORMAT	
'F Y'
You're seeing this error because you have DEBUG = True in your Django settings file. Change that to False, and Django will display a standard 500 page.

**Comment by babybunny** [comment]
I rolled back to previous version of the app, using the console.  This should not be a problem any more.

**Comment by caripang** [comment]
Thank you!

Cari Pang Chen | Associate Director



Rebuilding Together Peninsula
841 Kaynyne Street | Redwood City | 94063
(W): 650.366.6597 x224 | (C): 650.451-1787
www.RTPeninsula.org <http://www.rebuildingtogetherpeninsula.org/>

*A safe and healthy home for every person*

Note: When visiting our office, please note that we have a back parking lot
accessible via 852 Charter Street, between Bay & Spring.
