### ISSUE TITLE
Returns are doubling, not just crediting back exact amount

### ISSUE THREAD

**Issue by caripang** [babybunny/rebuildingtogethercaptain#258]
http://rebuildingtogethercaptain.appspot.com/room/site/list/5884520683274240/

We noticed that we tried to put in a return (-$15) for home depot, and ROOMS is crediting $30 instead of $15.

**Comment by babybunny** [comment]
I see the $15.  Where do you see the $30?

**Comment by caripang** [comment]
Weird.  Looks ok now.  I tried changing the amounts and it appears to be working correctly now.  Thanks for looking into it!
