### ISSUE TITLE
ROOMS priorities of items that need to be done - p2

### ISSUE THREAD

**Issue by babybunny** [babybunny/rebuildingtogethercaptain#263]
Broken edit/view ability for these items (we can see most of these items on the reporting summary but not see/edit the details):
**Orders
**Check Requests
**Vendor Receipts

Broken List overviews (** are most important):
** List all Sites and their Captains
** View a list of all Check Requests. 
** View a list of all Vendor Receipts.

**Comment by babybunny** [comment]
sites and captains works

**Comment by babybunny** [comment]
all works except for adding / editing items on orders

**Comment by caripang** [comment]
any update on when adding/editing orders might be possible?  We are tracking these manually for now.

still getting this result: 

Internal Server Error

The server has either erred or is incapable of performing the requested operation.

Traceback (most recent call last):
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1535, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1529, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1278, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1102, in __call__
    return handler.dispatch()
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 572, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 570, in dispatch
    return method(*args, **kwargs)
TypeError: get() got an unexpected keyword argument 'site'

**Comment by babybunny** [comment]
Sorry, I thought this has been fixed already.  Checking.

**Comment by babybunny** [comment]
opened an issue for it
https://github.com/babybunny/rebuildingtogethercaptain/issues/290

**Comment by babybunny** [comment]
This is going to be a bit involved because there are several screens for
making an order.  I'll work on it today and have an idea tomorrow about the
ETA.

I assume that it's most important to have the items and quantities now, and
I can skip the delivery logistics.

**Comment by babybunny** [comment]
I have a way to add and edit very simple orders without items and delivery
logistics.  Basically just enough to track the expenses per order.  There
is a way to override the order total amount without adding any items.

This can be wired up to the "place order" button if that will be useful.
Or it may be confusing.  Your call.

Adding items will take a while, like a week.

**Comment by caripang** [comment]
Hi Luke,

Just wondering if there's an update as to when the orders might be fixed
and if there's something that I can set up?  right now, having simple
orders without items and delivery logistics is fine, but we'll need that
set up for NRD in the spring.

aloha,
cari

**Comment by babybunny** [comment]
i belive these are all done
