### ISSUE TITLE
Google Maps links not working

### ISSUE THREAD

**Issue by caripang** [babybunny/rebuildingtogethercaptain#279]
Example: 
https://rebuildingtogethercaptain.appspot.com/room/site/view/6710963793297408/

When you click on the map, the following error shows up:

We could not find <bound method NewSite.StreetAddress of NewSite, announcement_body=u'Pat yourself on the back - no items need attention.\r\nYou have a clean bill of health.', announcement_subject=u'Nothing Needs Attention', applicant=None, applicant_email=None, applicant_home_phone=u'650 755 2771', applicant_mobile_phone=None, applicant_work_phone=None, budget=2500, city_state_zip=u'Daly City CA 94014', jurisdiction=u'Daly City', jurisdiction_choice=Key, latest_computed_expenses=1934.5999999999999, name=u'Linda and Michael McInerney', number=u'17502DAL', photo_link=None, program=u'2017 Safe', rating=None, roof=None, rrp_level=None, rrp_test=None, scope_of_work=u

**Comment by babybunny** [comment]
fixed
