### ISSUE TITLE
ROOMS Summary Print Formatting Issues

### ISSUE THREAD

**Issue by caripang** [babybunny/rebuildingtogethercaptain#280]
Strange text at top of Summaries when you print them - here's an example:
https://rebuildingtogethercaptain.appspot.com/room/site_summary/6710963793297408

ROOM System 2017 Safe change (/room/select_program) | Staff Home (/room/staff_home) | View Site Expenses
tps://rebuildingtogethercaptain.appspot.com/_ah/logout? %3Fcontinue%3Dhttps://appengine.google.com/_ah/logout%253Fcontinue%253Dhttps://rebuildingtogethercaptain.appspot.com/%26service%3Dah)

Site #17502DAL (/room/site/view/6710963793297408/) Reporting Summary

**Comment by babybunny** [comment]
got it
