### ISSUE TITLE
change item price within time range

### ISSUE THREAD

**Issue by babybunny** [babybunny/rebuildingtogethercaptain#296]
need a special flow for changing item price.  needs to alert that changing the price will affect the accounting for existing (past, back to beginning of time) orders.  offer alternative way to alter the price only going forward.  

will need to add valid date ranges to items.  

Billy is the expert on this one.

**Comment by babybunny** [comment]
the way to do this is to add a new item with the new price and retire the old item.
so we can do it manually today and I can make some tools to make it easier in the future (like "copy Item").
we'll also need to keep track of "lot numbers" for Items

**Comment by babybunny** [comment]
lot number is better thought of as "invoice"

**Comment by babybunny** [comment]
Another way to do this is to store the item price inside the order so it never changes.  this might be a lot easier because it allows users to simply update the item's price and then they don't have to worry about it affecting old orders.  

Maybe it gets copied in when the order gets fulfilled.  so if an item's price changes before fulfillment then you get the new price, but after it's fulfilled then the price is locked in.

**Comment by babybunny** [comment]
Actually I think this can be pretty simple.  I'll add a field to OrderItem which has the total cost (unit cost * quantity) for the items on a specific Order.  The number can be saved there.  

The Item model is more like an item in on a shopping site - it exists but can change over time.  The OrderItem is like an item that was shipped to you - it's attached to a specific Order and it has a price that can not change. 

Will need to change the logic for computing order totals as well.  If there is a need for updating past Orders then we can write some background jobs to do that, given a list of items, prices, and date periods the prices are effective.

**Comment by babybunny** [comment]
add a task to update the item price at a certain time in the future.  will need a new flow  for "change item price"

**Comment by MaryVeliz** [comment]
We have a fair amount of items, that we no longer carry in the Warehouse. I would like the item disappear from the order form so no one can order the item however,  I do not want to delete the item because we do not want to delete the historical data. How can I accomplish this task?

**Comment by andy-d** [comment]
Luke is IP (in progress) on this.

**Comment by babybunny** [comment]
Pushed a fix for this - item prices will be frozen at the value used when the order was submitted.   It's an improvement.
