### ISSUE TITLE
get people on github 

### ISSUE THREAD

**Issue by babybunny** [babybunny/rebuildingtogethercaptain#306]
Jo
Mary
Greg

**Comment by babybunny** [comment]
I emailed them.  

To get you set up with github accounts ... First step is for you to go to github and set up and account. 

https://github.com/join?source=header-repo
Use your rebuildingtogetherpeninsula.org email address.  Let me know when you've done it and then I'll add you to the ROOMS repository (aka code area).

**Comment by babybunny** [comment]
Jo and Greg are on.  Mary not yet.

**Comment by caripang** [comment]
Thanks - shall I e-mail Mary to have her sign up through github?



Cari Pang Chen | Associate Director



Rebuilding Together Peninsula
841 Kaynyne Street | Redwood City | 94063
(W): 650.366.6597 x224 | (C): 650.451-1787
www.RTPeninsula.org <http://www.rebuildingtogetherpeninsula.org/>

*A safe and healthy home for every person*

Note: When visiting our office, please note that we have a back parking lot
accessible via 852 Charter Street, between Bay & Spring.

**Comment by caripang** [comment]
confirmed that I sent Mary an e-mail to ask her to join GitHub using mary@rebuildingtogetherpeninsula.org and e-mail @babybunny when she has signed up.
