### ISSUE TITLE
add existing order dates and captains to order logistics

### ISSUE THREAD

**Issue by babybunny** [babybunny/rebuildingtogethercaptain#314]
I'm omitting them now for simplicity.

**Comment by caripang** [comment]
sounds good - thanks!   it's important to get those back in later as reference for reporting and for placing NRD orders in the future.

**Comment by babybunny** [comment]
this is for the screen where you are creating a new order - it shows the
logistics dates for the existing orders as a helpful reminder.

**Comment by caripang** [comment]
ok - i was just checking it out in the 2017 sample site (17000RWC).  Fine to remove past orders for now to simplify things.  Is it still possible to have the contact info for the captains show up as reference when the order fulfillment contact info is being added?

**Comment by babybunny** [comment]
pushing a fix for this now.  on the order logistics page you'll see the existing logistics and captains.  

I only had one space for Captain's phone number so I put in the mobile one.
