### ISSUE TITLE
No way to add Captains to a site

### ISSUE THREAD

**Issue by caripang** [babybunny/rebuildingtogethercaptain#341]
We appear to have lost the ability to add a captain to a project.  In this case, we have a captain "Don Kirk" that we'd like to add to Safe at Home projects that he is now working on, but there doesn't seem to be a way to do this anymore.

**Comment by babybunny** [comment]
I will grab the code part of this and work w/ Greg to test it. 

I have a saved copy of the old site edit page which has functions to add and remove captains. 

My code approach will be to create an API for adding/removing captains from a site.  Then create a UI element that does it and hook up the UI element to the Site View page and maybe other places (like the Site Edit and Captain Edit pages). The UI element will be implemented as a Backbone view, so I'll start getting into composition of pages that have several views. I'll read up a bit on techniques for that, including marionette.js https://marionettejs.com

**Comment by babybunny** [comment]
read marionettejs docs and decided it's overkill for this. the main benefit seems to be avoidance of redrawing entire pages when a small region covers the data which has changed.

**Comment by babybunny** [comment]
Adding Captains is now possible, at the bottom of the "edit site" page.
for example
https://rebuildingtogethercaptain-hrd.appspot.com/room/site/6372340115963904
