### ISSUE TITLE
pull scope of work (SoW) from SalesForce

### ISSUE THREAD

**Issue by babybunny** [babybunny/rebuildingtogethercaptain#368]
SalesForce has a version of the SoW.  ROOMS users copy/paste in the SoW today, before work is done, and then they edit the SoW at the end when the receive the expenses and see what actually happened. 

We need something about syncing scopes of work between the two systems, documenting the final scope. 

Proposed a way to sync final scope of work back to SalesForce.   Keep two fields in ROOMs as well, perhaps. 

Billy knows about the SalesForce side.

**Comment by caripang** [comment]
Just to clarify, the SOW coordination with ROOMS needs to be able to incorporate both what is generated by SAH through Salesforce (Billy can give an example) and what is created by the Captains/volunteers through their own separate form outside of Salesforce, which they don't have access too.

**Comment by jophillipsrtp** [comment]
Looks like this issue is up twice and the other one is being worked on, so this one can be deleted?

**Comment by billyrtp** [comment]
If its a duplicate, yeah, go ahead and delete it.


Billy Hoover | Operations & Impact Manager



Rebuilding Together Peninsula
841 Kaynyne Street | Redwood City | 94063
(W): 650.366.6597 x221 | (F): 650.366.9053
www.RebuildingTogetherPeninsula.org
<http://www.rebuildingtogetherpeninsula.org/>

*A safe and healthy home for every person*
