### ISSUE TITLE
Order Form & Item Visibility

### ISSUE THREAD

**Issue by caripang** [babybunny/rebuildingtogethercaptain#404]
@MaryVeliz would like to be able to clean up our order forms, and it would be helpful to hide certain orders so that other staff don't continue to use forms that we no longer want them to access.  

Currently, we have no way to delete order forms, but we can adjust visibility to "everyone" or "staff only" - is there a way to add a third level of "admin only" so that the form would not show up on the list for "everyone" or "staff only" when you go to a site and click on "Make an Order" but could still be seen when you look at "All Order Forms"?  

It would also be helpful to have a way to delete or hide visibility for items since currently there is only an option to edit existing items or add new ones.

**Comment by babybunny** [comment]
I've added, in addition to "Everyone" and "Staff Only" a new visibility  mode called "Inactive".  These order forms will only appear on the list of all order forms and you can set it on the edit page.
