### ISSUE TITLE
Fulfillment of orders

### ISSUE THREAD

**Issue by MaryVeliz** [babybunny/rebuildingtogethercaptain#427]
After creating an order from our Warehouse, I'm unable to reconcile or fulfill. It worked at 8AM however, now I'm receiving a error message.

Thanks

**Comment by babybunny** [comment]
Thanks Mary.  I looked in the logs and didn't see any errors.

Can you add the URL of the page you were viewing when you saw the error?    something like 

https://rebuildingtogethercaptain.appspot.com/room ....

I was able to go into the test program and fulfill and order.  One problem I found was that after fulfilling I was directed to an empty page.  Is that the error you saw?

**Comment by babybunny** [comment]
Actually I believe I saw the error on my development server, and I believe I've fixed it.  

It was after the Fulfill page where it prints, and the order got into the "Being Filled" state but the user was dumped into a page with an error about OrderByProgram not found.
