### ISSUE TITLE
Add an "upload Document" spot under Scope of Work Order

### ISSUE THREAD

**Issue by jophillipsrtp** [babybunny/rebuildingtogethercaptain#443]
Currently if we (staff or a captain) wants to get a scope of work onto ROOMs, they need to submit a scope via "orders" and type in the scope items, But I need there to be a spot (where in addition to typing in the scope) someone can upload an attached Doc, Excel, or PDF alternatively and then hit Submit.

**Comment by andy-d** [comment]
Looking into this now...

**Comment by andy-d** [comment]
@jophillipsrtp (FYSA @caripang) just to confirm for a v 1.0 you don't need the data in the document parsed to ROOMS fields just the document as unstructured data? Thanks.

**Comment by jophillipsrtp** [comment]
Hi Andy, If I understand the question correcting- No, I do not need any of the information within the uploaded document to go anywhere or do anything on ROOMs, Yes I just need there to be a way for documents to be attached and saved on ROOMS. Hope that answers what you're asking, but let me know if not (PS- So excited that this may be possible for Captains!) Thank you!

**Comment by babybunny** [comment]
I believe this is done.
