### ISSUE TITLE
Ability to submit Multiple "Scope of Work" orders 

### ISSUE THREAD

**Issue by jophillipsrtp** [babybunny/rebuildingtogethercaptain#444]
Currently with NRD, We need to track 3 different Scope of Work (SOW) because of how the process works. The first one is the "Recommended scope" that I make on Salesforce (in the past we just have printed this and given it to captains but I would like it to be on ROOMs for them to see from the start) ( So I need a way to upload a doc to ROOMs and submit as an Order, if we are not able to pull scopes from Salesforce directly); The second Scope is the "Approved Scope of work" which usually is sent to me as a PDF, because it was literally signed by the Home owner (if captains are able to upload a PDF while submitting this scope, that would fix this; and then third scope would be the "Final scope of work" which would reflect what actually was done at the home and would be used to send for our reporting purposes. So if there is a way where we can have captains or staff submit 3 different Scopes of work, each with its correct name, and each with ability to type in or upload attached PDF- that would be the goal!

**Comment by babybunny** [comment]
I believe this is done now.  There are 4 separate attachment fields for scope of work.
