### ISSUE TITLE
Create an inability to submit In-kind Donation without value 

### ISSUE THREAD

**Issue by jophillipsrtp** [babybunny/rebuildingtogethercaptain#447]
Problem is we get Captains who submit an in-kind Donation record, but do not give a value for that Donation and this info is useless without a value. Can we create a mandatory value needing to be added in order for them to submit? 

It would be good too if when then hit submit, if they have not put a value you, if a message would come up that would say something like "You can not submit an in-kind Donation without a Value. Please add an estimated Value or find out an estimated Value from the source and then submit. Values are very important for our reporting"

**Comment by babybunny** [comment]
Ok I think we can make this a required field.   I like that language, I'll see how to work it into the form.

**Comment by babybunny** [comment]
ok it's in place.
