### ISSUE TITLE
Cloud DataStore: Can position_name be in first column?

### ISSUE THREAD

**Issue by caripang** [babybunny/rebuildingtogethercaptain#452]
Currently position_name is in the last column, but that's usually what I need to see to know which Name/ID I need to edit.  Because I can't see all the columns on one screen, I have to look for the position name, then scroll back over blindly to pick the right Name/ID to edit.

Cloud DataStore
https://console.cloud.google.com/datastore/entities/query?project=rebuildingtogethercaptain-hrd&ns=&kind=StaffPosition&sortDir=DESCENDING&sortCol=position_name

**Comment by babybunny** [comment]
I can't change the datastore page, but there's a better solution which is to make screens to edit StaffPosition in ROOMS.  Tracked as issue 455
