### ISSUE TITLE
Site Page links do not appear to work for captains

### ISSUE THREAD

**Issue by caripang** [babybunny/rebuildingtogethercaptain#459]
Example: 
When I log into site #17625BEL as a captain with my personal e-mail/test account, I cannot get any of the "buttons" to work -
"Place an Order" "Submit a Request" "Add a Receipt" "Add a Donation" "View" "Make Changes"

However, these are accessible when I login as a staff person.

**Comment by babybunny** [comment]
Got orders working on a separate version.

https://issue459-dot-rebuildingtogethercaptain-hrd.appspot.com/room/captain_home

I'll push to production and then start working on the other types of buttons.

**Comment by babybunny** [comment]
orders works on prod.  

other forms load but do not work with the Captain field.

**Comment by babybunny** [comment]
all the expenses appear to work now.

the forms are a bit ugly- please file separate issues to fix them up :)
