### ISSUE TITLE
Attachment spot for "Runner Waiver"

### ISSUE THREAD

**Issue by jophillipsrtp** [babybunny/rebuildingtogethercaptain#473]
This is for NRD only. Similar to how there's a way now for captains and staff to upload attachments related tot he scope of work, can you all create a way for captains to upload the required Runner waiver form? I would imagine this similar to how you created the "scope of work Attachment" option for them, but it would say "Runner Waiver attachment." They would need the ability to upload our signed Runner waiver form, and possibly 2 other attachments with it, seeing as they need to also send us a scanned copy of their Driver's license, and a scanned copy of their car insurance. So this is a total of 3 attachments specifically for the Runner waiver upload. Let me know if this makes sense or if you have questions. (This is the end of adjusting anything relating to attachments FYI) and It would be awesome if this could be done by March 23rd, which is right before their deadline.  THANK YOU!!!

**Comment by andy-d** [comment]
This was fixed by https://github.com/babybunny/rebuildingtogethercaptain/commit/cababafbdeddbb791f7a0dce4eb3dfc1760ae39e

**Comment by andy-d** [comment]
For clarity these attachments are now on the same page as the statement of work ones - just further down

**Comment by jophillipsrtp** [comment]
THANK YOU!!!!!
