### ISSUE TITLE
view and edit links not working on captains view for orders, check requests, vendor receipts, or in-kind donations

### ISSUE THREAD

**Issue by billyrtp** [babybunny/rebuildingtogethercaptain#476]
From the captains view once an order, check request, or vendor receipt is submitted, the view link is not opening anything and is only refreshing the site page and the edit link is not visible/available

**Comment by babybunny** [comment]
fixed view link.  Allowing edits on check request, vendor receipt, in-kind donation.  edits on orders are available only before orders are filled.

**Comment by babybunny** [comment]
Greg: Quick question (hopefully).  Did the View option for Check Requests and Vendor Receipts go away recently?  I have printouts of Check Requests that I can no longer create and for the life of me I can't figure out how I did it if the option is still there.  The 'View' was what we turned into Jan for accounting purposes. 

Mary: 
I think the old version looked more professional. The current set up appears as a data entry page. Can we revert back to the old version?
