### ISSUE TITLE
Orders can't be changed

### ISSUE THREAD

**Issue by gregbernard** [babybunny/rebuildingtogethercaptain#481]

**Comment by jophillipsrtp** [comment]
Mary and Greg are trying to edit Orders and when they hit "make changes" this is what comes up:
Loading module for creating and changing orders ...  and nothing loads. This is critical to have working ASAP since they are fulfilling many orders today and this week and need to edit.

**Comment by babybunny** [comment]
I see. Should be an easy fix.

**Comment by babybunny** [comment]
fixed.  sorry about that one during the busy period.
