### ISSUE TITLE
No "View" option - only to "Make Changes"

### ISSUE THREAD

**Issue by caripang** [babybunny/rebuildingtogethercaptain#499]
Happy New Year!

We have noticed lately that we can create a new check request or vendor receipt, etc. but we cannot view it after it's been entered, only "make changes." 

See example: 
https://rebuildingtogethercaptain.appspot.com/room/site/view/5781189172396032/

**Comment by kate-mills** [comment]
Hi Cari! I see what you are talking about.  
Hopefully, this is what you want with the "view or edit" options.

See example:
https://issue499-dot-rebuildingtogethercaptain-hrd.appspot.com/room/site/view/5781189172396032/

**Comment by caripang** [comment]
Hi Kate,

Yes - thanks!  The view vs edit options are exactly what we seem to be
missing and would like to go back to.

aloha,
cari

**Comment by babybunny** [comment]
we deployed the fix during our meeting.  looks good now.
