### ISSUE TITLE
Paint order form doesn't allow for color specification and instructions dont' t match

### ISSUE THREAD

**Issue by billyrtp** [babybunny/rebuildingtogethercaptain#507]
<img width="995" alt="Screen Shot 2019-03-19 at 11 31 57 AM" src="https://user-images.githubusercontent.com/27710238/54632347-1d808a80-4a3b-11e9-9094-24da9ec687de.png">

**Comment by babybunny** [comment]
I'll add the feature to be able to specify color.  This seems important :)

**Comment by billyrtp** [comment]
Thanks Luke!

Billy Hoover | Manager, Operations & Impact


Rebuilding Together Peninsula
841 Kaynyne Street | Redwood City | 94063
(W): 650.366.6597 x221 | (F): 650.366.9053
www.RebuildingTogetherPeninsula.org
<http://www.rebuildingtogetherpeninsula.org/>

*Repairing Homes. Revitalizing Communities. Rebuilding Lives.*


* <https://www.facebook.com/RebuildingTogetherPeninsula>
<https://www.instagram.com/rtpeninsula/>
<https://twitter.com/RTPeninsula>
<https://www.youtube.com/user/RTPeninsula>*

Note: When visiting our office, please note that we have a back parking lot
accessible via 852 Charter Street
<https://maps.google.com/?q=852+Charter+Street&entry=gmail&source=g>,
between Bay & Spring.

**Comment by babybunny** [comment]
The features are done.  You may want to update the instructions on the Paint form.
