### ISSUE TITLE
import 2020 NRD data

### ISSUE THREAD

**Issue by babybunny** [babybunny/rebuildingtogethercaptain#538]
Cari sent the data via email.  I added it to drive.
https://drive.google.com/drive/folders/0B6-KkLeW-1wFZzBIUXVHVjdvMjQ

Will take a look now and try importing.

**Comment by babybunny** [comment]
created branch nrd2020 to track

**Comment by babybunny** [comment]
one item for Billy/Cari:  can you please review this and make sure it's up to date (as far as you can tell :)
https://github.com/babybunny/rebuildingtogethercaptain/wiki/Import-Site-and-Captain-Data

**Comment by babybunny** [comment]
going to set applicant and site name to the same thing.   data column: Homeowner/Site Contact Name

**Comment by babybunny** [comment]
the column seems to be unused:  CDBG Funding Source

**Comment by babybunny** [comment]
added Program Year column to the data, with value 2020

**Comment by babybunny** [comment]
when importing captain data: 
ERROR:root:site 20039EPA does not exist, skipping
ERROR:root:site 2008SAM does not exist, skipping
ERROR:root:site 20039EPA does not exist, skipping
ERROR:root:site 20039EPA does not exist, skipping

**Comment by babybunny** [comment]
please confirm:
2008SAM may be a typo for 20008SAM

20039EPA does not exist, file ends at 20038EPA

**Comment by caripang** [comment]
Yes - I think this looks correct and is what Billy helped to export and put
together this year.

Cari Pang Chen | Associate Director


Rebuilding Together Peninsula
841 Kaynyne Street | Redwood City | 94063
(W): 650.366.6597 x224 | (C): 650.451-1787
www.RTPeninsula.org <http://www.rebuildingtogetherpeninsula.org/>

*Repairing Homes. Revitalizing Communities. Rebuilding Lives.*

* <https://www.facebook.com/RebuildingTogetherPeninsula>
<https://www.instagram.com/rtpeninsula/>
<https://twitter.com/RTPeninsula>
<https://www.youtube.com/user/RTPeninsula>*

Note: When visiting our office, please note that we have a back parking lot
accessible via 852 Charter Street, between Bay & Spring.

**Comment by caripang** [comment]
2008SAM should be 20008SAM
20039EPA should be 20039PAL
Looks like the site data was not included though in the export for some
reason even though it was in Salesforce.

I manually inputted the info for 20039PAL and we seem ok now with 20008SAM
- thank you!!



Cari Pang Chen | Associate Director


Rebuilding Together Peninsula
841 Kaynyne Street | Redwood City | 94063
(W): 650.366.6597 x224 | (C): 650.451-1787
www.RTPeninsula.org <http://www.rebuildingtogetherpeninsula.org/>

*Repairing Homes. Revitalizing Communities. Rebuilding Lives.*

* <https://www.facebook.com/RebuildingTogetherPeninsula>
<https://www.instagram.com/rtpeninsula/>
<https://twitter.com/RTPeninsula>
<https://www.youtube.com/user/RTPeninsula>*

Note: When visiting our office, please note that we have a back parking lot
accessible via 852 Charter Street, between Bay & Spring.

**Comment by babybunny** [comment]
https://rebuildingtogethercaptain-hrd.appspot.com/room/sites_and_captains  
looks pretty good.  31 sites. 

confirmed w/ Billy it looks good.  closing.
